/**
 * This class is generated by jOOQ
 */
package sample.jooq.domain;


import javax.annotation.Generated;


/**
 * Convenience access to all tables in spring_boot_blog
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>spring_boot_blog.category</code>.
     */
    public static final Category CATEGORY = sample.jooq.domain.Category.CATEGORY;

    /**
     * The table <code>spring_boot_blog.category_post</code>.
     */
    public static final CategoryPost CATEGORY_POST = sample.jooq.domain.CategoryPost.CATEGORY_POST;

    /**
     * The table <code>spring_boot_blog.comment</code>.
     */
    public static final Comment COMMENT = sample.jooq.domain.Comment.COMMENT;

    /**
     * The table <code>spring_boot_blog.post</code>.
     */
    public static final Post POST = sample.jooq.domain.Post.POST;

    /**
     * The table <code>spring_boot_blog.tag</code>.
     */
    public static final Tag TAG = sample.jooq.domain.Tag.TAG;

    /**
     * The table <code>spring_boot_blog.user</code>.
     */
    public static final User USER = sample.jooq.domain.User.USER;
}
