package me.wonwoo.service;

import org.springframework.stereotype.Service;

@Service
public class TemplateService {

    public String getSetting() {
        return "{\n"
            + "  \"index\": {\n"
            + "    \"number_of_shards\": \"5\",\n"
            + "    \"refresh_interval\": \"10s\",\n"
            + "    \"analysis\": {\n"
            + "      \"analyzer\": {\n"
            + "        \"post_index_analyzer\": {\n"
            + "          \"type\": \"custom\",\n"
            + "          \"char_filter\": \"openkoreantext-normalizer\",\n"
            + "          \"tokenizer\": \"openkoreantext-tokenizer\",\n"
            + "          \"filter\": [\n"
            + "            \"openkoreantext-stemmer\",\n"
            + "            \"openkoreantext-redundant-filter\",\n"
            + "            \"index_synonym\",\n"
            + "            \"stop\",\n"
            + "            \"length\",\n"
            + "            \"lowercase\",\n"
            + "            \"asciifolding\",\n"
            + "            \"porter_stem\"\n"
            + "          ]\n"
            + "        }\n"
            + "      },\n"
            + "      \"filter\": {\n"
            + "        \"index_synonym\": {\n"
            + "          \"type\": \"synonym\",\n"
            + "          \"synonyms\": [\n"
            + "            \"스프링 => spring\",\n"
            + "            \"스프링 부트, 스프링부트=> spring boot\",\n"
            + "            \"네티 => netty\",\n"
            + "            \"스레드 => thread\",\n"
            + "            \"자바 => java\",\n"
            + "            \"오토컨피그, 오토컨피그레이션 => AutoConfiguration\",\n"
            + "            \"웹 => web\",\n"
            + "            \"어노테이션, 애노테이션 => Annotation\",\n"
            + "            \"빈 => Bean\",\n"
            + "            \"비동기 => Async\",\n"
            + "            \"바이트코드 => bytecode\",\n"
            + "            \"클래스 => class\",\n"
            + "            \"인터페이스 => interface\",\n"
            + "            \"메서드, 메소드 => method\",\n"
            + "            \"레포지토리 => repository\",\n"
            + "            \"컴포넌트. 컴퍼넌트 => component\",\n"
            + "            \"서비스 => service\",\n"
            + "            \"서버 => Server\"\n"
            + "          ]\n"
            + "        }\n"
            + "      }\n"
            + "    }\n"
            + "  }\n"
            + "}";
    }

    public String getMapping() {
        return "{\n"
            + "  \"post\": {\n"
            + "    \"properties\": {\n"
            + "      \"post_title\": {\n"
            + "        \"type\": \"text\",\n"
            + "        \"store\": \"true\",\n"
            + "        \"analyzer\": \"post_index_analyzer\"\n"
            + "      },\n"
            + "      \"post_author\": {\n"
            + "        \"type\": \"text\",\n"
            + "        \"store\": \"true\",\n"
            + "        \"index\": \"false\"\n"
            + "      },\n"
            + "      \"post_content\": {\n"
            + "        \"type\": \"text\",\n"
            + "        \"store\": \"true\",\n"
            + "        \"term_vector\": \"with_positions_offsets\",\n"
            + "        \"analyzer\": \"post_index_analyzer\"\n"
            + "      },\n"
            + "      \"post_type\": {\n"
            + "        \"type\": \"text\",\n"
            + "        \"store\": \"true\",\n"
            + "        \"index\": \"false\"\n"
            + "      },\n"
            + "      \"post_status\": {\n"
            + "        \"type\": \"text\",\n"
            + "        \"store\": \"true\",\n"
            + "        \"index\": \"false\"\n"
            + "      },\n"
            + "      \"post_content_filtered\": {\n"
            + "        \"type\": \"text\",\n"
            + "        \"store\": \"true\",\n"
            + "        \"term_vector\": \"with_positions_offsets\",\n"
            + "        \"analyzer\": \"post_index_analyzer\"\n"
            + "      },\n"
            + "      \"post_date\": {\n"
            + "        \"type\": \"date\",\n"
            + "        \"store\": \"true\",\n"
            + "        \"index\": \"true\"\n"
            + "      },\n"
            + "      \"highlightedContent\": {\n"
            + "        \"type\": \"text\",\n"
            + "        \"store\": \"true\",\n"
            + "        \"term_vector\": \"with_positions_offsets\"\n"
            + "      },\n"
            + "      \"tableOfContent\": {\n"
            + "        \"type\": \"text\",\n"
            + "        \"store\": \"true\",\n"
            + "        \"index\": \"true\"\n"
            + "      }\n"
            + "    }\n"
            + "  }\n"
            + "}";
    }
}
